# Generated by Django 4.0.4 on 2022-06-27 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0002_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='options',
            name='option',
        ),
        migrations.DeleteModel(
            name='Award',
        ),
        migrations.DeleteModel(
            name='Options',
        ),
    ]
