# Generated by Django 4.0.4 on 2022-07-01 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='description_text',
            field=models.CharField(default='an award', max_length=200),
        ),
    ]
