# Generated by Django 4.0.4 on 2022-07-01 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0005_award_description_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='upload',
            field=models.ImageField(default='midyearsotbawards/awards/static/awards/img/mdb-favicon.ico', upload_to='midyearsotbawards/awards/useruploads'),
        ),
    ]
