# Generated by Django 4.0.4 on 2022-07-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0006_award_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='options',
            name='nominee_image',
            field=models.ImageField(default='midyearsotbawards/awards/static/awards/img/mdb-favicon.ico', upload_to='awards/static/awards/img/nominees'),
        ),
        migrations.AlterField(
            model_name='award',
            name='upload',
            field=models.ImageField(default='midyearsotbawards/awards/static/awards/img/mdb-favicon.ico', upload_to='awards/static/awards/useruploads'),
        ),
    ]
